PUT http://localhost:8080/events/4
Content-Type: application/json

{
    "Name" : "Updated Event",
    "Description" : "A test event (updated !)",
    "Location" : "A test location",
    "DateTime" : "2025-01-01T15:30:00.000Z"
}